# Generated by Django 5.1.2 on 2024-10-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adonaiapp', '0002_product_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_db',
            old_name='category_name',
            new_name='category_name1',
        ),
    ]
