# Generated by Django 5.1.2 on 2024-10-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_db',
            old_name='subject',
            new_name='lname',
        ),
        migrations.RemoveField(
            model_name='contact_db',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact_db',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact_db',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
