# Generated by Django 5.1.2 on 2024-11-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_order_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_db',
            name='Totalprice',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
