# Generated by Django 5.1.2 on 2024-11-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_order_db_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_db',
            name='Totalprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_db',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
